config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#index'
  get  'contact' => 'static_pages#contact'
  get  'about' => 'static_pages#profile'
  get  'services' => 'static_pages#services'
  resources :projects , only: [:show, :index], path: 'works' 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
class Image < ActiveRecord::Base
  #attr_accessible :project_id, :image
  belongs_to :project
  mount_uploader :name, ImageUploader

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :type
  belongs_to :year
  has_many :services
  has_many :images
  # attr_accessible :image
  # mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :images, :services, :year, :type, allow_destroy: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :project
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :projects
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @project_service = @project.services
    @web_images = @project.images.where(category: "web")
    @tab_images = @project.images.where(category: "tab")
    @phone_images = @project.images.where(category: "phone")
    @header_images = @project.images.where(category: "header")
    @thumbnail_images = @project.images.where(category: "thumbnail")
    
  end
  
  def index 
    @projects = Project.all

  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  
  def contact
  end
  
  def profile
  end
  
  def services
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rakarsa</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<div id="main" class="m-scene">
      <div class="header">
        <section class="nav">
          <a href="#cd-nav" class="cd-nav-trigger">Menu
            <span class="cd-nav-icon"></span>

            <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
              <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
            </svg>
          </a>

          <div id="cd-nav" class="cd-nav">
            <div class="cd-navigation-wrapper">
              <div class="cd-half-block">

                <nav class="cl-effect-13">
                  <ul class="cd-primary-nav">
                    <li><img src="<%= asset_path 'logo_only_bk.svg' %>"></li>
                    <li><%= link_to "WORKS",   projects_path %></li>
                    <li><%= link_to "ABOUT",   about_path %></li>
                    <li><%= link_to "SERVICES",   services_path %></li>
                    <li><%= link_to "CONTACT",   contact_path %></li>
                  </ul>
                </nav>
              </div><!-- .cd-half-block -->
    
            </div> <!-- .cd-navigation-wrapper -->
          </div>
        </section>
      </div>
      
      <div id="fullpage-works">
        <div class="section" id="section1">
          <section id="works" class="cover">
            <div class="desc">
              <h1 class="gotham cl-effect-2">
                <%= link_to(root_path) do%>
                  <span data-hover="Back">WORKS</span>
                <% end %>
              </h1>
              <div class="strip">
              -
              </div>
              <p>What is done and undone will be a story and that is why we decide to tell our story. We hope our story will fascinate others and draw them close. Well, if not today then someday will.</p>
              <a href="#secondPage"><img src="<%= asset_path 'cd-icon-arrow-desktop.svg' %>" style="display:block; margin:0 auto"></a>
            </div>
          </section>
        </div>
        
        <div class="section" id="section2">
          <section id="work">
            <ul id="masonry-container" class="port large-block-grid-2">
              <% @projects.each do |project|%>
              <li class='box'>
                <%= link_to (project_path(project)) do %>
                  <%= image_tag(project.images.find_by(category: 'thumbnail').name.url)%>
                
                <div class="overlay"><br />
                  
                  <span><%= project.project_title %></span> <br />
                  <span class ="kecil"><%= project.client_name %></span>
                </div>
              </li>
                <% end %>
              <% end %>
            </ul>
          </section>
        </div>  
      </div>
    
    <script>
      $(window).load(function(){
        $('#masonry-container').masonry({
          itemSelector: '.box',
          gutterWidth: 40
        });
      });
    </script>
    

app/views/projects/show.html.erb
<div id="main" class="container">
      <div class="header">
        <section class="nav">
          <a href="#cd-nav" class="cd-nav-trigger">Menu
            <span class="cd-nav-icon"></span>

            <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
              <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
            </svg>
          </a>

          <div id="cd-nav" class="cd-nav">
            <div class="cd-navigation-wrapper">
              <div class="cd-half-block">

                <nav class="cl-effect-13">
                  <ul class="cd-primary-nav">
                    <li><img src="<%= asset_path 'logo_only_bk.svg' %>"></li>
                    <li><%= link_to "WORKS",   projects_path %></li>
                    <li><%= link_to "ABOUT",   about_path %></li>
                    <li><%= link_to "SERVICES",   services_path %></li>
                    <li><%= link_to "CONTACT",   contact_path %></li>
                  </ul>
                </nav>
              </div><!-- .cd-half-block -->
              
            </div> <!-- .cd-navigation-wrapper -->
          </div>
        </section>
      </div>
    </div>

    <section id="img">
    <%- @header_images.each do |header| %>

        <%=  image_tag(header.name.url)%>
    
    <% end %>
    </section>

    <section id="detail">
      <div class="row" style="max-width: 74vw">
        <div id="pro1" class="large-9 column">
          <h1><%=@project.client_name %></h1>
          <h2><%=@project.project_title %></h2>
          <hr>
          <p><%= @project.description %></p>
        </div>

        <div id="pro1" class="type large-3 column">
          <h2>TYPE</h2>
          <hr>
          <p><%= @project.type.name %></p>
          <h2>Year</h2>
          <hr>
          <p><%= @project.year.release_year %></p>
        </div>
      </div>
   
     <div id="pro1" class="row" style="max-width: 74vw">
       <div class="large-9 column">
         <h2>Services</h2>
         <hr>
         <ul class="servi">
           <%- @project_service.each do |service| %>
           <li><%= service.name %></li>
           <% end %>
         </ul>
       </div>
     </div>
   </section>
       
    <br>
    
   <section id="preview">
     <%- @web_images.each do |web| %>
     <div class="row" style="max-width: 74vw">
       <div class="large-12 column">
         <%=  image_tag(web.name.url)%>
       </div>
     </div>
     <% end %>
     
     
     <div class="row" style="max-width: 74vw">
       <%- @tab_images.each do |tab| %>
       <div class="large-6 column">
         <%= image_tag(tab.name.url)%>
       </div>
       <% end %>
     </div>
     
     <div class="row" style="max-width: 74vw">
       <%- @phone_images.each do |phone| %>
       <div class="large-4 column">
         <%= image_tag(phone.name.url) %>
       </div>
       <% end %>
     </div>
   </section> 

app/views/static_pages/contact.html.erb
<div id="main" class="m-scene">
      <div class="header">
        <section class="nav">
          <a href="#cd-nav" class="cd-nav-trigger">Menu
            <span class="cd-nav-icon"></span>

            <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
              <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
            </svg>
          </a>

          <div id="cd-nav" class="cd-nav">
            <div class="cd-navigation-wrapper">
              <div class="cd-half-block">

                <nav class="cl-effect-13">
                  <ul class="cd-primary-nav">
                    <li><img src="<%= asset_path 'logo_only_bk.svg' %>"></li>
                    <li><%= link_to "WORKS",   projects_path %></li>
                    <li><%= link_to "ABOUT",   about_path %></li>
                    <li><%= link_to "SERVICES",   services_path %></li>
                    <li><%= link_to "CONTACT",   contact_path %></li>
                  </ul>
                </nav>
              </div><!-- .cd-half-block -->
              
            </div> <!-- .cd-navigation-wrapper -->
          </div>
        </section>
      </div>

    <div id="fullpage-contact">
      <div class="section" id="section1">
        <section id="contact" class="cover">
          <div class="desc">
            <!-- <img src="img/logo_only_bk.svg"> -->
            <h1 class="gotham cl-effect-2">
                  <%= link_to(root_path) do%>
                    <span data-hover="Back">Contact Us</span>
                  <% end %>
            </h1>
              <div class="strip">
              -
              </div>
            <p>Curiosity and knowledge gives us the opportunities to answer every problems we are facing, so why not do it for cause then. 
            We are ready to give our best efforts to you, feel free to collaborate with us.</p>
            <a href="#secondPage"><img src="<%= asset_path 'cd-icon-arrow-desktop.svg' %>" style="display:block; margin:0 auto"></a>
          </div>
        </section>
      </div>

      <div class="section" id="section2">
        <section id="cont">
          <div id="map" style='height: 50vh; margin-top: -65px'>
            <script type="text/javascript">
              $( document ).ready(function(){
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            
                markers = handler.addMarkers([
                  {
                    "lat": -6.86784,
                    "lng": 107.62795,

                    "infowindow": "Jl. Rancakendal Luhur 11, Dago Pakar, Bandung , Jawa Barat 40191"
                  }
                ]);
              
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(16);
              
              
               
             

              
                });
              });
            </script>
          </div>

          <div id="kontak" class="row">
            <div class="medium-4 large-4 column">
              <h1>Contact</h1>
              -
                <ul>
                  <li>E. hello@rakarsa.com</li>
                  <li>P. +62 856 2424 3612</li>
                </ul>

                <p>Jl. Rancakendal Luhur 11</br>
                Dago Pakar, Bandung 40198</p>
            </div>

            <div class="medium-4 large-4 column">
              <h1>Social</h1>
              -
                <ul>
                  <li>Facebook</li>
                  <li>Twitter</li>
                  <li>Instagram</li>
                  <li>Pinterest</li>
                </ul>
            </div>

            <div class="medium-4 large-4 column">
              <img src="<%= asset_path 'logo_only_bk.svg' %>">
            </div>
          </div>

        </section>
      </div>
    </div>
    
  
 <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
 <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>   

app/views/static_pages/index.html.erb
<div id="main" class="m-scene">
      <div class="header">
        <section class="nav">
          <a href="#cd-nav" class="cd-nav-trigger">Menu
            <span class="cd-nav-icon"></span>

            <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
              <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
            </svg>
          </a>

          <div id="cd-nav" class="cd-nav">
            <div class="cd-navigation-wrapper">
              <div class="cd-half-block">
                <nav class="cl-effect-13" id="offmenu">
                  <ul class="cd-primary-nav">
                    <li><img src="<%= asset_path 'logo_only_bk.svg' %>"></li>
                    <li><%= link_to "WORKS",   projects_path %></li>
                    <li><%= link_to "ABOUT",   about_path %></li>
                    <li><%= link_to "SERVICES",   services_path %></li>
                    <li><%= link_to "CONTACT",   contact_path %></li>
                  </ul>
                </nav>
              </div><!-- .cd-half-block -->
            </div> <!-- .cd-navigation-wrapper -->
          </div>
        </section>
      </div>
      <div id="fullpage-home">
        <div class="section" id="section1">
          <section id="home" class="hero">
            <div class="inner">
              <img src="<%= asset_path 'logo_only_bk.svg' %>">
              <h1 class="slim">WE ARE</h1>
              <h1 class="bold">RAKARSA</h1>
              <p>"User Experience is our concern"</p>
            </div>
            <a href="#navigation"><img src="<%= asset_path 'cd-icon-arrow-desktop.svg' %>" style="display:block; margin:0 auto"></a>
          </section>
        </div>
        <div class="section" id="section2">
          <section id="menu">
            <ul class="large-block-grid-4 medium-block-grid-1 small-block-grid-1">
              <li>
                <%= link_to(projects_path) do %>
                <div id="mnu" class="link link--takiri1">
                  <div class="mnu-title">
                    <h2>WORKS</h2>  
                  </div>
                </div>
                <% end %>
              </li>
              <li>
                <%= link_to(about_path) do %>
                <div id="mnu1" class="link link--takiri2">
                  <div class="mnu-title">
                    <h2>ABOUT</h2>
                  </div>
                </div>
                <% end %>
              </li>
              <li>
                <%= link_to(services_path) do %>
                <div id="mnu2" class="link link--takiri3">
                  <div class="mnu-title">
                    <h2>SERVICES</h2>
                  </div>
                </div>
                <% end %>
              </li>
              <li>
                <%= link_to(contact_path) do %>
                <div id="mnu3" class="link link--takiri4">
                  <div class="mnu-title">
                    <h2>CONTACT</h2>
                  </div>
                </div>
                <% end %>
              </li>
            </ul>
              <canvas id="canv"></canvas>
          </section>
        </div>
      </div>
</div>

app/views/static_pages/profile.html.erb
<div id="main" class="m-scene">
      <div class="header">
        <section class="nav">
          <a href="#cd-nav" class="cd-nav-trigger">Menu
            <span class="cd-nav-icon"></span>

            <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
              <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
            </svg>
          </a>

          <div id="cd-nav" class="cd-nav">
            <div class="cd-navigation-wrapper">
              <div class="cd-half-block">

                <nav class="cl-effect-13">
                  <ul class="cd-primary-nav">
                    <li><img src="<%= asset_path 'logo_only_bk.svg' %>"></li>
                    <li><%= link_to "WORKS",   projects_path %></li>
                    <li><%= link_to "ABOUT",   about_path %></li>
                    <li><%= link_to "SERVICES",   services_path %></li>
                    <li><%= link_to "CONTACT",   contact_path %></li>
                  </ul>
                </nav>
              </div><!-- .cd-half-block -->
              
            </div> <!-- .cd-navigation-wrapper -->
          </div>
        </section>
      </div>

      <div id="fullpage-profile">
        <div class ="section" id="section1">
          <section id="about" class="cover">
            <div class="desc">
              <h1 class="gotham cl-effect-2">
                <%= link_to(root_path) do%>
                  <span data-hover="Back">ABOUT US</span>
                  <% end %>
              </h1>
              <div class="strip">
              -
              </div>
              <p>Rakarsa is a short form of "Rodha Among Karsa", taken from sanskrit language which means "a circle that keep and nurture an idea and a passion to create".</p>
              <p>As human being, we have dreams that we want to pursue. We want to actualize ourselves create something and nurture them until become the great things that thrive others or just gives us a smile for awhile.</p>
              <a href="#secondPage"><img src="<%= asset_path 'cd-icon-arrow-desktop.svg' %>" style="display:block; margin:0 auto"></a>
            </div>
          </section>
        </div>

        <div class="section" id="section2">
          <section id="profile">
            <div class="prof">
              <h1>Behind The Scene</h1>
              <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-4">
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Ghiyaats Muhammad</h2>
                <h3>Creative Director</h3>
                -
                <p>cool // noob stark // photographer </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Reza Jatnika</h2>
                <h3>Project Manager</h3>
                -
                <p>geek // hehe wepe // master</p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Dewi Kartika Syarif</h2>
                <h3>Content Writer</h3>
                -
                <p> // // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Aan Yohanis</h2>
                <h3>Account Manager</h3>
                -
                <p> // // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Kahirul</h2>
                <h3>Senior Developer</h3>
                -
                <p>geek // // traveler</p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Azmy ansori</h2>
                <h3>Senior Developer</h3>
                -
                <p>all rounder // bedul koflok // patient</p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>M Ali Murtopo</h2>
                <h3>Junior Developer</h3>
                -
                <p> // tymee // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Pradipto</h2>
                <h3>Junior Developer</h3>
                -
                <p> // // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Tri Adi Wirawan</h2>
                <h3>Senior Developer</h3>
                -
                <p> // rie // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Hamzah</h2>
                <h3>Junior Developer</h3>
                -
                <p>all rounder // insomnia // geek</p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Tri Puspita Pratiwi</h2>
                <h3>Financial Manager</h3>
                -
                <p> // // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Anggia Riksa R</h2>
                <h3>Junior Developer</h3>
                -
                <p> // dep // </p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Morian Saspriatnadi</h2>
                <h3>Creative Designer</h3>
                -
                <p>architect // master // photographer</p>
                </li>
                <li><img src="<%= asset_path 'avatar.jpg' %>">
                <h2>Candra Wana</h2>
                <h3>Strategist</h3>
                -
                <p> // cdr // </p>
                </li>
              </ul>
            </div>
          </section>
        </div>
      </div>

app/views/static_pages/services.html.erb
<div id="main" class="m-scene">
      <div class="header">
        <section class="nav">
          <a href="#cd-nav" class="cd-nav-trigger">Menu
            <span class="cd-nav-icon"></span>

            <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
              <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
            </svg>
          </a>

          <div id="cd-nav" class="cd-nav">
            <div class="cd-navigation-wrapper">
              <div class="cd-half-block">

                <nav class="cl-effect-13">
                  <ul class="cd-primary-nav">
                    <li><img src="<%= asset_path 'logo_only_bk.svg' %>"></li>
                    <li><%= link_to "WORKS",   projects_path %></li>
                    <li><%= link_to "ABOUT",   about_path %></li>
                    <li><%= link_to "SERVICES",   services_path %></li>
                    <li><%= link_to "CONTACT",   contact_path %></li>
                  </ul>
                </nav>
              </div><!-- .cd-half-block -->
              
            </div> <!-- .cd-navigation-wrapper -->
          </div>
        </section>
      </div>

      <div id="fullpage-services">
        <div class="section" id="section1">
          <section id="services" class="cover">
            <div class="desc">
              <h1 class="gotham cl-effect-2">
                <%= link_to(root_path) do%>
                  <span data-hover="Back">SERVICES</span>
                <% end %>
              </h1>
              <div class="strip">
              -
              </div>
              <p>We focus on web design & development. People, community, or companies with great value deserves good publicity and exposure. We will give our best kind of support and appreciation in anyway we can to those who.</p>
              <a href="#secondPage"><img src="<%= asset_path 'cd-icon-arrow-desktop.svg' %>" style="display:block; margin:0 auto"></a>
            </div>
          </section>
        </div>

        <div class="section" id="section2">
          <section id="service">
            <div class="serv">
              <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3">
                <li><img src="<%= asset_path 'services.png' %>">
                <h2>Strategy</h2>
                <p>Research
                  <br>
                  Concept Development
                  <br>
                  Project Planning
                  <br>
                  User Experience
                </p>
                </li>
                <li><img src="<%= asset_path 'services.png' %>">
                <h2>Creative</h2>
                <p>
                  Content Strategy
                  <br>
                  User Interface Design
                  <br>
                  Web Design
                  <br>
                  Branding
                  <br>
                  Logo
                </p>
                </li>
                <li><img src="<%= asset_path 'services.png' %>">
                <h2>Technology</h2>
                <p>
                  Frontend
                  <br>
                  Backend
                  <br>
                  Prototyping
                  <br>
                  Cross-platform
                  <br>
                  Web-App
                </p>
                </li>
              </ul>
            </div>
          </section>
        </div>

        <div class="section" id="section3">
          <section id="service" class="cover">
            <div class="desc">
              <h1 class="gotham">Process</h1>
              <p>We believe, the proper environment and the appropriate process, we can bring out the best of our works. Our plan are designed with definite objectives so we can help you giving the best experiences, designs, and solutions with ideas & values within.</p>
            </div>
          </section>
        </div>

        <div class="section" id="section4">
          <section id="service">
            <div class="row serv data-equalizer">
              <div class="small-6 large-4 column data-equalizer-watch upper">
                <img src="<%= asset_path 'process.png' %>">
                <h2>Discover</h2>
                <p>We aim to give our client best possible solution and design. We would seek several alternatives that could possibly implemented. We always seek a comprehensive information by finding precedents & inspirations. And yes our client is our inspiration.</p>
              </div>
              <div class="small-6 large-4 column data-equalizer-watch upper">
                <img src="<%= asset_path 'process.png' %>">
                <h2>Define</h2>
                <p>We invest significant time and efforts in developing and implementating a knowledge base which is technology and arts that offers uniques perspectives and insights. We would formulate the ideas and concepts into wireframe. You could validate the offered concepts, features, and wireframe.</p>
              </div>
              <div class="small-6 large-4 column data-equalizer-watch upper">
                <img src="<%= asset_path 'process.png' %>">
                <h2>Design</h2>
                <p>We have great team in this part.We bring art and technology into one unity body. Collaboration between designer, developer, and client are the key factor of design phase. By putting on the detail, we give the design its personality and character into some mockup. We develop the choosen mockup into the real design, deliver the final polished design into graphics detail</p>
              </div>
            </div>
            <div class="row serv data-equalizer">
              <div></div>
              <div class="small-6 large-centered column data-equalizer-watch lower">
                <img src="<%= asset_path 'process.png' %>">
                <h2>Develop</h2>
                <p>We spend countless hours in order to transform the beauty of graphics into a poem of code. Mix a good cup of coffee, upbeat music, and some snacks to our table. We would never let the piece of our works delivered without passing some criteria and quality. We'll deliver a satisfyng results.</p>
              </div>
              <div class="small-6 large-centered column data-equalizer-watch lower">
                  <img src="<%= asset_path 'process.png' %>">
                <h2>Deliver</h2>
                <p>Finally our work hard work is almost done. We hope that our product could help our partner meet their goals. We believe that every beginning has an end, but not this one. We hope that we could work together on another opportunity</p>
              </div>
              <div></div>
            </div>
          </section>
        </div>
      </div>
</div>